### PR TITLE
fix: textarea autoheight not working

### LINKED ISSUE #68: 修改评论时，text area的高度没有自动变高
image

在里面打一个字会让高度变得正常

image

### PR DESCRIPTION
**Pull request by shaokeyibb**
fix #68

### CODE REVIEW

File: frontend/lib/main.ts [hunk 1]
```diff
@@ -497,12 +497,17 @@ const _renderComments = (comments: Comment[]) => {
       </div>
     `.trim();
 
+    const _updateTextareaHeight = (textarea: HTMLTextAreaElement) => {
+      textarea.style.height = "5px";
+      console.log(textarea.scrollHeight);
```
Comment (Enter-tainer) [inline frontend/lib/main.ts:502]: log 可以去掉？

**Review by Enter-tainer — APPROVED** [review]
